import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  filamentsSidebar: [{
    type: "autogenerated",
    dirName: "filaments"
  }],
};

export default sidebars;
